### ISSUE TITLE
Write PriceOracleMock.sol

### ISSUE THREAD

**Issue by jasonklein** [OpenSTFoundation/openst-payments#19]
To facilitate testing.

Relates to #2.

**Comment by benjaminbollen** [comment]
`ConstantPriceOracleMock` can return a constant price point for all currencies;
1. first tests POMock by providing an intended price point within the pricer-defined margins
2. second set of tests calls on Pricer/Airdrop with intendedPricePoint deliberately set outside of the range of the Pricer margin; hence testing the failure scenarios
3. to test expiration of price points, use ConstantPriceOracleMock with price point set to 0

**Comment by jasonklein** [comment]
Resolved by #58.
